- name: Check if Helm is already installed
  stat:
    path: "{{helm_install_dir}}/helm"
  register: helm_result
  become: yes

- name: Gather Helm version
  shell: helm version -c
  when: helm_result.stat.exists == True
  register: helm_version_command
  changed_when: false
  failed_when: false

- when: helm_result.stat.exists == False or helm_version_command is undefined or helm_version not in helm_version_command.stdout 
  block:
    - name: Download Helm
      get_url: 
        url: "{{helm_mirror}}/helm-{{ helm_version }}-{{ helm_platform }}.tar.gz"
        dest: /tmp/helm-{{ helm_version }}-{{ helm_platform }}.tar.gz

    - name: Create extraction directory
      file:
        path: /tmp/helm-{{ helm_version }}
        state: directory
        mode: 0755

    - name: Unarchive Helm
      unarchive: 
        remote_src: yes
        src: /tmp/helm-{{ helm_version }}-{{ helm_platform }}.tar.gz
        dest: /tmp/helm-{{ helm_version }}

    - name: Include Helm in /usr/local/bin/
      copy:
        remote_src: yes
        src: /tmp/helm-{{ helm_version }}/{{ helm_platform }}/helm
        dest: "{{helm_install_dir}}/helm"
        mode: 0755
      become: yes
      
  always:
    - name: Cleanup tmp files
      become: yes
      file:
        path: /tmp/helm-{{ helm_version }}-{{ helm_platform }}.tar.gz
        state: absent



