- name: Check if Tiller service exists
  shell: kubectl get pods -n kube-system | grep tiller
  changed_when: false
  failed_when: false
  register: tiller_service

- when: tiller_service is failed or tiller_service.rc != 0
  name: Start Tiller service
  block:
    - name: Copy Tiller account configuration
      template:
        src: tiller-rbac.yml
        dest: /tmp/

    - name: Create Tiller account
      command: kubectl create -f /tmp/tiller-rbac.yml
 
    - name: Init Helm
      command: helm init --service-account tiller

    - name: Wait for Tiller to start
      shell: kubectl get pods -n kube-system | grep tiller
      register: tiller_status
      until: tiller_status.stdout.find("1/1") != -1
      retries: 50
      delay: 10
  always:
    - name: Cleanup tmp files
      become: yes
      file:
        path: /tmp/tiller-rbac.yml
        state: absent
